import {
  urlsIngrid,
  urlsJazmin,
  urlsSyM,
  urlsDelfina,
  urlsComplejoQuinta,
  urlsMia,
  urlsBianca,
  urlsLara,
  urlsMichelin,
  urlsEstela,
  urlsEnergia,
  urlsAbril,
  urlsClubPesca,
  urlsCami,
  urlsEmpresarialMA,
  urlsColegioNacional,
} from "./images";

export const events = [
  {
    image: urlsIngrid[0],
    images: urlsIngrid,
    title: "Ingrid & Leo Sociedad Rural",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "2025-04-23",
  },
  {
    image: urlsJazmin[0],
    images: urlsJazmin,
    title: "Jazmín",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "2025-05-10",
  },
  {
    image: urlsSyM[0],
    images: urlsSyM,
    title: "S & M",
    description: "Fiesta de casamiento",
    type: "Boda",
    date: "2025-03-02",
  },
  {
    image: urlsDelfina[0],
    images: urlsDelfina,
    title: "Delfina",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "2025-01-15",
  },
  {
    image: urlsComplejoQuinta[0],
    images: urlsComplejoQuinta,
    title: "Evento en Complejo Quinta",
    description: "Fiesta social",
    type: "Evento",
    date: "2025-02-28",
  },
  {
    image: urlsMia[0],
    images: urlsMia,
    title: "Mía",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "2025-06-07",
  },
  {
    image: urlsBianca[0],
    images: urlsBianca,
    title: "Bianca",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "2025-06-14",
  },
  {
    image: urlsLara[0],
    images: urlsLara,
    title: "Lara",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "2025-04-06",
  },
  {
    image: urlsMichelin[0],
    images: urlsMichelin,
    title: "Michelin",
    description: "Evento corporativo",
    type: "Empresarial",
    date: "2025-05-20",
  },
  {
    image: urlsEstela[0],
    images: urlsEstela,
    title: "Estela",
    description: "Cumpleaños familiar",
    type: "Cumpleaños",
    date: "2025-03-30",
  },
  {
    image: urlsEnergia[0],
    images: urlsEnergia,
    title: "Energía",
    description: "Evento corporativo",
    type: "Empresarial",
    date: "2025-04-12",
  },
  {
    image: urlsAbril[0],
    images: urlsAbril,
    title: "Abril",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "2025-02-10",
  },
  {
    image: urlsClubPesca[0],
    images: urlsClubPesca,
    title: "Club de Pesca",
    description: "Fiesta social",
    type: "Evento",
    date: "2025-01-27",
  },
  {
    image: urlsCami[0],
    images: urlsCami,
    title: "Cami",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "2025-03-22",
  },
  {
    image: urlsEmpresarialMA[0],
    images: urlsEmpresarialMA,
    title: "Evento MA",
    description: "Evento corporativo",
    type: "Empresarial",
    date: "2025-06-01",
  },
  {
    image: urlsColegioNacional[0],
    images: urlsColegioNacional,
    title: "Colegio Nacional",
    description: "Evento escolar",
    type: "Escolar",
    date: "2025-05-05",
  },
];

export const slugify = (str) =>
  str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
