import {
  urlsIngrid,
  urlsJazmin,
  urlsSyM,
  urlsDelfina,
  urlsComplejoQuinta,
  urlsMia,
  urlsBianca,
  urlsLara,
  urlsMichelin,
  urlsEstela,
  urlsEnergia,
  urlsAbril,
  urlsClubPesca,
  urlsCami,
  urlsEmpresarialMA,
  urlsColegioNacional,
  urlsCatia,
  urlsTami,
  urlsMiguel,
  urlsValentina,
  urlsPyM,
  urlsSofia,
  urlsAlexyMili,
  urlsVaneyFran,
  urlsSole,
  urlsMoni,
  urlsPaz,
  urlsSofiPlacente,
  urlsDagnaJoaquin,
  urlsSindicatoLuzFuerza,
  urlsTukerIriarte,
  urlsAymiHubert,
} from "./images";

export const events = [
  {
    image: urlsIngrid[0],
    images: urlsIngrid,
    title: "Ingrid & Leo Sociedad Rural",
    description: "Fiesta de casamiento",
    type: "Casamientos",
    date: "23/04/2025",
  },
  {
    image: urlsJazmin[0],
    images: urlsJazmin,
    title: "XV de Jazmín",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "06/04/2025",
  },
  {
    image: urlsSyM[0],
    images: urlsSyM,
    title: "Santi & Mica",
    description: "Fiesta de casamiento",
    type: "Casamientos",
    date: "29/03/2025",
  },
  {
    image: urlsDelfina[0],
    images: urlsDelfina,
    title: "XV de Delfina",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "06/04/2025",
  },
  {
    image: urlsComplejoQuinta[0],
    images: urlsComplejoQuinta,
    title: "XV de María Paz",
    description: "Fiesta de 15 años en Complejo Quinta",
    type: "Cumpleaños",
    date: "15/03/2025",
  },
  {
    image: urlsMia[0],
    images: urlsMia,
    title: "XV de Mía",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "09/03/2025",
  },
  {
    image: urlsBianca[0],
    images: urlsBianca,
    title: "XV de Bianca",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "09/03/2025",
  },
  {
    image: urlsLara[0],
    images: urlsLara,
    title: "Lara",
    description: "Noche mágica Lara",
    type: "Eventos",
    date: "09/03/2025",
  },
  {
    image: urlsMichelin[0],
    images: urlsMichelin,
    title: "Michelin",
    description: "Evento corporativo",
    type: "Empresarial",
    date: "21/01/2025",
  },
  {
    image: urlsEstela[0],
    images: urlsEstela,
    title: "60 años de Estela",
    description: "Cumpleaños familiar",
    type: "Cumpleaños",
    date: "21/01/2025",
  },
  {
    image: urlsEnergia[0],
    images: urlsEnergia,
    title: "EDES",
    description:
      "Evento corporativo de empresa distribuidora de la energía EDES",
    type: "Empresarial",
    date: "21/01/2025",
  },
  {
    image: urlsAbril[0],
    images: urlsAbril,
    title: "XV de Abril",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "20/01/2025",
  },
  {
    image: urlsClubPesca[0],
    images: urlsClubPesca,
    title: "Club de Pesca Huanguelén",
    description: "Fiesta social",
    type: "Eventos",
    date: "20/01/2025",
  },
  {
    image: urlsCami[0],
    images: urlsCami,
    title: "XV de Cami",
    description: "Fiesta de 15 años",
    type: "Cumpleaños",
    date: "09/01/2025",
  },
  {
    image: urlsEmpresarialMA[0],
    images: urlsEmpresarialMA,
    title: "Evento Martín Alarcia",
    description: "Evento corporativo",
    type: "Empresarial",
    date: "09/01/2025",
  },
  {
    image: urlsColegioNacional[0],
    images: urlsColegioNacional,
    title: "Colegio Nacional",
    description: "Egreso del Colegio Nacional promo 2024",
    type: "Escolares",
    date: "22/12/2024",
  },
  {
    image: urlsCatia[0],
    images: urlsCatia,
    title: "Katia Fest",
    description: "Noche mágica de Katia",
    type: "Eventos",
    date: "21/10/2024",
  },
  {
    image: urlsTami[0],
    images: urlsTami,
    title: "XV de Tamara",
    description: "Cumpleaños de 15 años",
    type: "Cumpleaños",
    date: "30/09/2024",
  },
  {
    image: urlsMiguel[0],
    images: urlsMiguel,
    title: "70 años de Miguel",
    description: "Cumpleaños de 70 años",
    type: "Cumpleaños",
    date: "27/08/2024",
  },
  {
    image: urlsValentina[0],
    images: urlsValentina,
    title: "XV de Valentina",
    description: "Cumpleaños de 15 años",
    type: "Cumpleaños",
    date: "01/08/2024",
  },
  {
    image: urlsPyM[0],
    images: urlsPyM,
    title: "Pame & Pablo",
    description: "Casamiento de Pame y Pablo",
    type: "Casamientos",
    date: "07/07/2024",
  },
  {
    image: urlsSofia[0],
    images: urlsSofia,
    title: "XV de Sofia",
    description: "Cumpleaños de 15 años",
    type: "Cumpleaños",
    date: "26/06/2024",
  },
  {
    image: urlsAlexyMili[0],
    images: urlsAlexyMili,
    title: "Alex & Mili",
    description: "Casamiento de Alex y Mili",
    type: "Casamientos",
    date: "12/03/2023",
  },
  {
    image: urlsVaneyFran[0],
    images: urlsVaneyFran,
    title: "Vane & Fran",
    description: "Casamiento de Vane y Fran",
    type: "Casamientos",
    date: "08/02/2023",
  },
  {
    image: urlsSole[0],
    images: urlsSole,
    title: "40 años de Soledad Torre",
    description: "Cumpleaños de 40 años",
    type: "Cumpleaños",
    date: "18/10/2022",
  },
  {
    image: urlsMoni[0],
    images: urlsMoni,
    title: "Monica",
    description: "Cumpleaños de Monica",
    type: "Cumpleaños",
    date: "23/05/2022",
  },
  {
    image: urlsPaz[0],
    images: urlsPaz,
    title: "XV de Paz",
    description: "Cumpleaños de 15",
    type: "Cumpleaños",
    date: "13/02/2023",
  },
  {
    image: urlsSofiPlacente[0],
    images: urlsSofiPlacente,
    title: "XV de Sofi Placente",
    description: "Cumpleaños de 15 en Salon Dorado",
    type: "Cumpleaños",
    date: "24/05/2025",
  },
  {
    image: urlsDagnaJoaquin[0],
    images: urlsDagnaJoaquin,
    title: "Dagna & Joaquín",
    description: "Casamiento en Complejo la Quinta",
    type: "Casamientos",
    date: "09/02/2025",
  },
  {
    image: urlsSindicatoLuzFuerza[0],
    images: urlsSindicatoLuzFuerza,
    title: "Sindicato Luz y Fuerza",
    description: "Evento en el salon Magnolia Eventos",
    type: "Eventos",
    date: "19/07/2025",
  },
  {
    image: urlsTukerIriarte[0],
    images: urlsTukerIriarte,
    title: "Tuker Iriarte",
    description: "Evento empresarial en campo La pista",
    type: "Empresarial",
    date: "18/07/2025",
  },
  {
    image: urlsAymiHubert[0],
    images: urlsAymiHubert,
    title: "XV de Aymi Hubert",
    description: "Cumpleaños de 15 en Salon Magnolia Eventos",
    type: "Cumpleaños",
    date: "12/07/2025",
  },
];

export const slugify = (str) =>
  str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
